site_name: Hexo-Theme-Last

nav:
  - 主题介绍: index.md
  - 安装:
    - 下载: download.md
    - 更新: upgrade.md
  - 使用: 
    - 主要页面: page.md
    - 基本配置: config.md
    - 第三方功能: functions.md

theme:
  # language: zh
  name: material
  palette:
  - scheme: default
    toggle: 
      icon: material/lightbulb-outline
      name: Switch to dark mode
    primary: black  
  - scheme: slate
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
    primary: black  
    # accent: light blue
  features:
    - navigation.expand
    - navigation.top
  logo: assets/images/favicon.png
extra:
  homepage: https://hexo-theme-last.github.io
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - minify
  - i18n:
      docs_structure: folder
      languages:
          - locale: zh
            name: 中文
            build: true
            default: true
          - locale: en
            default: true
            name: English
            build: true
            nav:
              - Introduction: index.md
              - Install:
                - Download: download.md
                - Update: upgrade.md
              - Usage: 
                - Main Page: page.md
                - Basic Configuration: config.md
                - Third-party Functions: functions.md
